{{- if and (index .Values "cert-manager" "issuer" "enabled") (ne (index .Values "cert-manager" "issuer" "acmeExternalAccountKey") "" ) }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cert-manager-external-account-key
  {{- if ne (index .Values "cert-manager" "issuer" "namespaceOverride") "" }}
  namespace: {{ index .Values "cert-manager" "issuer" "namespaceOverride" | quote }}
  {{- else }}
  namespace: {{ index .Values "cert-manager" "namespace" | quote }}
  {{- end }}
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: 'true'
spec:
  encryptedData:
    acme_external_account_key: {{ index .Values "cert-manager" "issuer" "secrets" "acmeExternalAccountKey" }}
  template:
    type: Opaque
{{- end }}
