{{- if index .Values "cert-manager" "issuer" "enabled" }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cert-manager-dns01-key
  {{- if ne (index .Values "cert-manager" "issuer" "namespaceOverride") "" }}
  namespace: {{ index .Values "cert-manager" "issuer" "namespaceOverride" | quote }}
  {{- else }}
  namespace: {{ index .Values "cert-manager" "namespace" | quote }}
  {{- end }}
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: 'true'
spec:
  encryptedData:
    secret_access_key: {{ index .Values "cert-manager" "issuer" "secrets" "dnsSecretAccessKey" }}
  template:
    type: Opaque
{{- end }}