{{- if index .Values "cert-manager" "issuer" "enabled" }}
apiVersion: cert-manager.io/v1
kind: {{ index .Values "cert-manager" "issuer" "kind" }}
metadata:
  name: {{ index .Values "cert-manager" "issuer" "name" }}
  {{- if ne (index .Values "cert-manager" "issuer" "namespaceOverride") "" }}
  namespace: {{ index .Values "cert-manager" "issuer" "namespaceOverride" | quote }}
  {{- else }}
  namespace: {{ index .Values "cert-manager" "namespace" | quote }}
  {{- end }}
spec:
  acme:
    email: {{ index .Values "cert-manager" "issuer" "email" }}
    server: {{ index .Values "cert-manager" "issuer" "acmeServer" }}
    {{- if ne (index .Values "cert-manager" "issuer" "acmeExternalAccountKeyId") "" }}
    externalAccountBinding:
      keyID: {{ index .Values "cert-manager" "issuer" "acmeExternalAccountKeyId" }} 
      keySecretRef:
        name: cert-manager-external-account-key
        key: acme_external_account_key
    {{- end }}
    privateKeySecretRef:
      name: acme-private-key
    solvers:
      - selector: {}
        dns01:
          {{- if eq (index .Values "cert-manager" "issuer" "dnsProvider") "route53" }}
          route53:
            region: {{ index .Values "cert-manager" "issuer" "route53Region" }}
            accessKeyID: {{ index .Values "cert-manager" "issuer" "route53AccessKeyId" }}
            secretAccessKeySecretRef:
              name: cert-manager-dns01-key
              key: secret_access_key
            {{- if ne (index .Values "cert-manager" "issuer" "route53HostedZoneId") "" }}
            hostedZoneID: {{ index .Values "cert-manager" "issuer" "route53HostedZoneId" }}
            {{- end }}
          {{- end }}
          {{- if eq (index .Values "cert-manager" "issuer" "dnsProvider") "cloudflare" }}
          cloudflare:
            email: {{ index .Values "cert-manager" "issuer" "email" }}
            apiTokenSecretRef:
              name: cert-manager-dns01-key
              key: secret_access_key
          {{- end }}
{{- end }}
