{{- if not (index .Values "cert-manager" "skipNamespace") }}
{{- if or (index .Values "cert-manager" "enabled") (index .Values "cert-manager" "issuer" "enabled") }}
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
{{- end }}
{{- end }}