---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: merit
  namespace: flux-system
spec:
  gitImplementation: go-git
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: merit
  timeout: 1m0s
  url: https://github.com/cybertrol-engineering/CE.Deployments.Merit.Winnipeg.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: dependencies
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./clusters/idmz/dependencies
  prune: true
  sourceRef:
    kind: GitRepository
    name: merit
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: idmz
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./clusters/idmz/apps
  prune: true
  sourceRef:
    kind: GitRepository
    name: merit
